/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WebSocketMessage =
  | MsgStatusUpdate
  | MsgChatDelta
  | MsgSuggestionsUpdate
  | MsgArtifactOpen
  | MsgArtifactUpdate;
export type Type = "STATUS_UPDATE";
export type SystemStatus = "idle" | "thinking" | "working" | "success";
export type Message = string;
export type Type1 = "CHAT_DELTA";
export type Payload = string;
export type Type2 = "SUGGESTIONS_UPDATE";
export type Payload1 = string[];
export type Type3 = "ARTIFACT_OPEN";
export type Id = string;
export type ArtifactType = "code" | "markdown" | "json" | "html" | "pdf" | "mermaid" | "workbook" | "stories";
export type Title = string;
export type Content = string;
export type Language = string | null;
export type Type4 = "ARTIFACT_UPDATE";
export type Id1 = string;
export type Content1 = string;
export type Id2 = string;
export type Priority = "High" | "Medium" | "Low";
export type Estimate = string;
export type Role = string;
export type Action = string;
export type Benefit = string;
export type Description = string;
export type Goal = string;
export type Scope = string[];
export type Outofscope = string[];
export type Acceptancecriteria = string[];
export type Stories = UserStory[];
export type Id3 = string;
export type Title1 = string;
export type Icon = string | null;
export type Id4 = string;
export type Text = string;
export type Items = WorkbookItem[];
export type Categories = WorkbookCategory[];

export interface FrontendContract {
  websocket_message: WebSocketMessage;
  user_story_data: UserStoryData;
  workbook_data: WorkbookData;
  [k: string]: unknown;
}
export interface MsgStatusUpdate {
  type: Type;
  payload: StatusUpdatePayload;
}
export interface StatusUpdatePayload {
  status: SystemStatus;
  message: Message;
}
export interface MsgChatDelta {
  type: Type1;
  payload: Payload;
}
export interface MsgSuggestionsUpdate {
  type: Type2;
  payload: Payload1;
}
export interface MsgArtifactOpen {
  type: Type3;
  payload: Artifact;
}
export interface Artifact {
  id: Id;
  type: ArtifactType;
  title: Title;
  content: Content;
  language?: Language;
}
export interface MsgArtifactUpdate {
  type: Type4;
  payload: ArtifactUpdatePayload;
}
export interface ArtifactUpdatePayload {
  id: Id1;
  content: Content1;
}
export interface UserStoryData {
  stories: Stories;
}
export interface UserStory {
  id: Id2;
  priority: Priority;
  estimate: Estimate;
  role: Role;
  action: Action;
  benefit: Benefit;
  description?: Description;
  goal?: Goal;
  scope: Scope;
  outOfScope: Outofscope;
  acceptanceCriteria: Acceptancecriteria;
}
export interface WorkbookData {
  categories: Categories;
}
export interface WorkbookCategory {
  id: Id3;
  title: Title1;
  icon?: Icon;
  items: Items;
}
export interface WorkbookItem {
  id: Id4;
  text: Text;
}
